### ISSUE TITLE
Archive on F-Droid?

### ISSUE THREAD

**Issue by TheLastProject** [UnifiedPush/gotify-android#10]
Seeing the note about this being unmaintained, does the app still have any use to people? Or should it be moved from the main F-Droid repo to F-Droid Archive so that new users aren't likely to install it anymore?

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12202

**Comment by p1gp1g** [comment]
We were waiting to see if anyone wanted to maintain this fork. It has been months. I think we can move it to the repository now. Thank you for pointing that out.

**Comment by TheLastProject** [comment]
Understandable, it's a shame nobody came forward, I quite liked using the app (but I don't have the time to maintain this myself). Moved to archive.
