### ISSUE TITLE
create pull request to upstream

### ISSUE THREAD

**Issue by genofire** [UnifiedPush/gotify-android#2]
When it is released?
It will be nice to have just one app and merge it fork

**Comment by p1gp1g** [comment]
The gotify developer prefers to wait. It was first merged into another branch but it was even harder to maintain than a fork and we couldn't be published on the main fdroid repo.

If you want to ask on their repo, I think the place is this issue: https://github.com/gotify/android/issues/29

**Comment by p1gp1g** [comment]
Gotify-UP is deprecated for ntfy, and the upstream project don't plan to merge it. So I'm closing it :)

**Comment by hydrargyrum** [comment]
Sorry, i didn't understand what is the reason of the deprecation, could you clarify?
