### ISSUE TITLE
Bad request: cannot register

### ISSUE THREAD

**Issue by stemy2** [UnifiedPush/gotify-android#5]
Hello,

I tried to register to the fedilab's gotify instance, but i can't because of the said error.

**Comment by p1gp1g** [comment]
I have just tried and succeeded to register on fedilab's gotify (https://gotify.fedilab.app).

If you still encounter this issue, the right place to troubleshoot it will be on the matrix room https://matrix.to/#/#fedilab_android:matrix.org (https://matrix.to/#/#unifiedpush:matrix.org is ok too) or by pm https://toot.fedilab.app/@apps
