### ISSUE TITLE
Problem with F-Droid repository?

### ISSUE THREAD

**Issue by EdoSecco** [UnifiedPush/gotify-android#6]
I'm testing the F-Droid repositories listed [here](https://forum.f-droid.org/t/known-repositories/721), and it seems that [UnifiedPush's one](https://repo.unifiedpush.org/?fingerprint=DF11176406C63A7876103CE6CC1A8FCA239DF76AA5F6DE5CDBAFE73ECDBF1875) could not be properly read by F-Droid app.

Thank you!

**Comment by jugendhacker** [comment]
Seems like it was removed because all apps are in the main repo now: https://fosstodon.org/@unifiedpush/107342640989240819

**Comment by p1gp1g** [comment]
> Seems like it was removed because all apps are in the main repo now: https://fosstodon.org/@unifiedpush/107342640989240819

This issue can be closed for this reason
